import e from"react";import{View as t}from"@tarojs/components";import r from"@tarojs/taro";function o(e,t){void 0===t&&(t={});var r=t.insertAt;if(e&&"undefined"!=typeof document){var o=document.head||document.getElementsByTagName("head")[0],s=document.createElement("style");s.type="text/css","top"===r&&o.firstChild?o.insertBefore(s,o.firstChild):o.appendChild(s),s.styleSheet?s.styleSheet.cssText=e:s.appendChild(document.createTextNode(e))}}o(".demo-text{font-size:40px}");const s=()=>e.createElement(t,{className:"demo"},e.createElement(t,{className:"demo-text"},"11111222"));
/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */function i(e){var t,r,o="";if("string"==typeof e||"number"==typeof e)o+=e;else if("object"==typeof e)if(Array.isArray(e))for(t=0;t<e.length;t++)e[t]&&(r=i(e[t]))&&(o&&(o+=" "),o+=r);else for(t in e)e[t]&&(o&&(o+=" "),o+=t);return o}o(".zc-switch{position:relative;display:inline-block;box-sizing:content-box;width:80px;height:40px;font-size:30px;background-color:#fff;border:1px solid rgba(0,0,0,.1);border-radius:40px;cursor:pointer;transition:background-color .3s}.zc-switch.disabled{cursor:not-allowed;opacity:.5}.zc-switch-checked{background-color:#5caaf8}.zc-switch-checked .zc-switch-box{transform:translateX(40px)}.zc-switch-box{position:absolute;top:0;left:0;width:38px;height:38px;background-color:#fff;border-radius:100%;box-shadow:1px 3px 1px 1px rgba(0,0,0,.1),1px 2px 2px 1px rgba(0,0,0,.1),1px 3px 3px 1px rgba(0,0,0,.1);transition:transform .3s cubic-bezier(.3,1.05,.4,1.05)}");const n=o=>{const{prefixCls:s="zc-switch",className:n,size:c="24",disabled:a,type:d="block"}=o,l=function(e,t){var r={};for(var o in e)Object.prototype.hasOwnProperty.call(e,o)&&t.indexOf(o)<0&&(r[o]=e[o]);if(null!=e&&"function"==typeof Object.getOwnPropertySymbols){var s=0;for(o=Object.getOwnPropertySymbols(e);s<o.length;s++)t.indexOf(o[s])<0&&Object.prototype.propertyIsEnumerable.call(e,o[s])&&(r[o[s]]=e[o[s]])}return r}(o,["prefixCls","className","size","disabled","type"]),[p,h]=e.useState(o.checked);e.useEffect((()=>{h(!!o.checked)}),[o.checked]);const f=(e,t,o)=>`${r.pxTransform((parseInt(String(e))-o)*t)}`,b=e.useMemo((()=>"block"===d?{width:f(c,4,0),height:f(c,2,0),borderRadius:3}:{width:f(c,4,0),height:f(c,2,0),borderRadius:f(c,2,0)}),[c,d]),m=e.useMemo((()=>"block"===d?p?{width:f(c,2,1),height:f(c,2,1),transform:`translateX(${r.pxTransform(2*parseInt(String(c)))})`,borderRadius:3}:{width:f(c,2,1),height:f(c,2,1),borderRadius:3}:{width:f(c,2,1),height:f(c,2,1)}),[c,p,d]),u=function(){for(var e,t,r=0,o="";r<arguments.length;)(e=arguments[r++])&&(t=i(e))&&(o&&(o+=" "),o+=t);return o}(s,n,{[`${s}-checked`]:p,disabled:a});return e.createElement(t,Object.assign({className:u,onClick:()=>{return e=p,void(a||(h(!e),null===(t=null==o?void 0:o.onChange)||void 0===t||t.call(o,!e)));var e,t}},{style:b},l),e.createElement(t,Object.assign({className:`${s}-box`},{style:m})))};export{s as Demo,n as Switch};
//# sourceMappingURL=index.esm.js.map
